### ISSUE TITLE
Incorrect repo name

### ISSUE THREAD

**Issue by SammySkycrafts** [Uchi-craft-room/FA-18E_CVW5#1]
The repo name is incorrect meaning when it is downloaded or cloned then a blue/yellow glider loads rather than the rhino. I would recommend that the repo is renamed, or the paths are changed to reflect the different name.

The main folder needs renaming from FA-18E-CVW5 to FA-18E_CVW5

**Comment by Uchi-craft-room** [comment]
Thank you for your contact.
 Changed the name of the repository from  FA-18E-CVW5 to FA-18E_CVW5.
